import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import DebounceInput from "@/components/DebounceInput";

const inter = Inter({ subsets: ["latin"] });
export interface stateProps {
  value: string;
  loading: boolean;
  num: number;
  users: string[];
  search: string;
}
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DebounceInput value={""} loading={false} num={0} users={[]} search={""} />
      </main>
    </>
  );
}
